# Generated by Django 6.0.1 on 2026-01-21 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_order_orderitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="order",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="product",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
    ]
