# Generated by Django 6.0.1 on 2026-01-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_category_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="logo",
            field=models.FileField(upload_to="brands/"),
        ),
    ]
