# Generated by Django 6.0.1 on 2026-01-24 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_product_is_new"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productphoto",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="catalog.product",
            ),
        ),
    ]
