# Generated by Django 6.0.1 on 2026-01-24 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_alter_productphoto_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeroBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="hero/", verbose_name="Изображение"),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Большой текст"),
                ),
                ("subtitle", models.TextField(verbose_name="Малый текст")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активный"),
                ),
            ],
            options={
                "verbose_name": "Титульник",
                "verbose_name_plural": "Титульники",
            },
        ),
    ]
