# Generated by Django 6.0.1 on 2026-01-24 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_heroblock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="heroblock",
            name="title",
            field=models.TextField(max_length=255, verbose_name="Большой текст"),
        ),
    ]
