# Generated by Django 6.0.1 on 2026-01-30 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0013_cart_updated_at_favorite"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="selected_params",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
