# Generated by Django 6.0.1 on 2026-01-31 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0015_cartitem_size_alter_cartitem_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together=set(),
        ),
    ]
