# Generated by Django 6.0.1 on 2026-01-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_auth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="photo_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
